### ISSUE TITLE
iCloud 15.2 Broke Windows Support

### ISSUE THREAD

**Issue by espiox** [au2001/icloud-passwords-firefox#46] opened 2024-08-09 10:43 UTC
After installing the latest iCloud for Windows update (15.2) which adds support for Shared Passwords, the extension simply returns an error:

>Error
>An unknown error occurred. Make sure you have the latest version of the extension installed. If the error persists, please try restarting Firefox.

**Comment by Kryzya** [comment] 2024-09-12 20:07
Any update? I have the same problem

**Comment by valsamis-d** [comment] 2024-10-03 19:25
I get a different error:

![image](https://github.com/user-attachments/assets/3621cea0-121e-458f-ae9f-73fdb30ce505)

**Comment by v-127** [comment] 2024-10-20 14:15
> I get a different error:
> 
> ![image](https://private-user-images.githubusercontent.com/17590539/373388451-3621cea0-121e-458f-ae9f-73fdb30ce505.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzQwMzEsIm5iZiI6MTcyOTQzMzczMSwicGF0aCI6Ii8xNzU5MDUzOS8zNzMzODg0NTEtMzYyMWNlYTAtMTIxZS00NThmLWFlOWYtNzNmZGIzMGNlNTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDE0MTUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ODcxNzI1NDY2YzQyMzlhZWQ2NTUwYWJmM2UwNjdlMjc0OWJmM2NjMjI1ZWFkZmVlOTM5MDBlNzI4YjIzOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IUN0M6HKLj5w2qNB0caZ7oOuSxFdI31qWBEUx6QdmOQ)

I'm having the same issue
![imagen](https://github.com/user-attachments/assets/12a4618c-b73d-4989-ae6f-583511a4bada)

**Comment by betam4x** [comment] 2024-11-13 16:53
Yep, definitely appears to be broken.

**Comment by au2001** [comment] 2024-12-02 12:47
Duplicate of #40

**Closed by au2001** 2024-12-02 12:47 UTC

**Comment by espiox** [comment] 2024-12-02 12:55
FYI my installation wasn't from the MS Store, and was just in the default install location (C:\Program Files\Mozilla Firefox). Also, the extension had been working completely fine until the morning that iCloud updated to 15.2.
