### ISSUE TITLE
addon on Windows 11 won't work.

### ISSUE THREAD

**Issue by MoaiGuy** [au2001/icloud-passwords-firefox#38] opened 2024-05-11 15:05 UTC
Hey, i tried installing the addon as the guide said, did also install the icloud-passwords-firefox-install-windows.exe as admin and i still get this,
![image](https://github.com/au2001/icloud-passwords-firefox/assets/50660570/6e2fd105-40c2-496e-9032-c2b3afdf3396)

i have both tried restarting firefox and windows but no dice.

am on winsdows 11.

and i have the newest build from https://addons.mozilla.org/en-US/firefox/addon/icloud-passwords/ 1.2.1 installed

**Comment by AnthonySchuijlenburg** [comment] 2024-06-11 18:14
I just installed this addon on Firefox in Windows 11 without problems. Could your problem be related to [ this issue](https://github.com/au2001/icloud-passwords-firefox/issues/40)? In other words, have you tried reinstalling Firefox (int the default location) from [here](https://www.mozilla.org/nl/firefox/new)?

**Comment by MoaiGuy** [comment] 2024-06-11 19:23
Thats the thing i never installed it via the Microsoft Store, but directly from mozillas own site

**Comment by AnthonySchuijlenburg** [comment] 2024-06-12 17:10
Since I'm not the maintainer nor a contributor to this package and just trying to help, I am just suggesting some things. Did you do step 4 while having the prompt of step 3 still open?

3. Click on `Install Extension...` for either Microsoft Edge or Google Chrome.
4. Download the `icloud_passwords_install` file from the [latest GitHub Release](https://github.com/au2001/icloud-passwords-firefox/releases/latest).

If you did and still don't have any luck, could you try reinstalling Firefox, or trying to install this plugin on a different pc?

**Comment by MoaiGuy** [comment] 2024-06-12 18:55
Will report back :)

**Comment by AnthonySchuijlenburg** [comment] 2024-06-24 21:30
Any updates?

**Comment by MoaiGuy** [comment] 2024-07-01 19:26
nope still don't work

**Comment by AnthonySchuijlenburg** [comment] 2024-07-05 13:12
Unfortunately then, I am out of ideas... I hope the creator of this repo is able to help you further!

**Comment by tollfree** [comment] 2024-11-10 22:06
This error only occurs if you authorize this extension when the default (empty) Firefox page is active.
Simply open any website you are certain you have saved the password for, and you will see that this extension was successfully authorized.

This is undoubtedly a bug

**Comment by au2001** [comment] 2024-12-02 12:47
Duplicate of #40

**Closed by au2001** 2024-12-02 12:47 UTC

**Comment by ctrlMarcio** [comment] 2024-12-03 08:54
> This error only occurs if you authorize this extension when the default (empty) Firefox page is active. Simply open any website you are certain you have saved the password for, and you will see that this extension was successfully authorized.
> 
> This is undoubtedly a bug
> 
> macOS 15.1 Firefox 132.0.1 Extension 1.2.2

This worked for me
