### ISSUE TITLE
Extensions does not work on Windows11 

### ISSUE THREAD

**Issue by f250gto** [au2001/icloud-passwords-firefox#43] opened 2024-06-23 15:32 UTC
Hi au2001,
I have followed the instruction to install the extension on windows 11.
But I receive the error that the extension requires iCloud for windows.
I have already installed iCloud for windows from MS Store before to configure the extension.
Please let me know if I can try additional step to unlock the extension.
Thanks,

**Comment by au2001** [comment] 2024-12-02 12:47
Duplicate of #40

**Closed by au2001** 2024-12-02 12:47 UTC
